# Generated by Django 4.2.7 on 2026-05-14 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='Mon Etablissement', max_length=200)),
                ('institution_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('institution_address', models.TextField(blank=True)),
                ('institution_phone', models.CharField(blank=True, max_length=30)),
                ('institution_email', models.EmailField(blank=True, max_length=254)),
                ('academic_year', models.CharField(default='2024-2025', max_length=20)),
                ('alert_threshold', models.FloatField(default=30.0)),
                ('critical_threshold', models.FloatField(default=50.0)),
                ('justification_deadline_days', models.IntegerField(default=7)),
                ('allow_student_register', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parametres systeme',
            },
        ),
        migrations.CreateModel(
            name='Rappel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rappel_type', models.CharField(choices=[('absence', 'Absence'), ('session', 'Seance'), ('justification', 'Justification')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('reminder_date', models.DateTimeField()),
                ('is_sent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rappel',
                'ordering': ['reminder_date'],
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_user', 'Creation utilisateur'), ('delete_user', 'Suppression utilisateur'), ('update_user', 'Modification utilisateur'), ('validate_justif', 'Validation justification'), ('reject_justif', 'Rejet justification'), ('import_excel', 'Import Excel'), ('update_settings', 'Modification parametres'), ('add_absence', 'Ajout absence manuel'), ('other', 'Autre')], max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log d action',
                'ordering': ['-created_at'],
            },
        ),
    ]
