# Generated by Django 4.2.7 on 2026-04-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('absence', 'Absence'), ('justification', 'Justification'), ('alert', 'Alerte'), ('info', 'Information'), ('prediction', 'Prédiction')], default='info', max_length=20),
        ),
    ]
