# Generated by Django 4.2.7 on 2026-04-22 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Département',
            },
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-created_at'], 'verbose_name': 'Présence'},
        ),
        migrations.AlterModelOptions(
            name='justification',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Justification'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Module'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date', '-start_time'], 'verbose_name': 'Séance'},
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('late', 'En retard'), ('justified', 'Absences justifiée')], default='absent', max_length=10),
        ),
        migrations.AlterField(
            model_name='justification',
            name='reason',
            field=models.CharField(choices=[('medical', 'Raison médicale'), ('family', 'Raison familiale'), ('transport', 'Problème de transport'), ('administrative', 'Raison administrative'), ('other', 'Autre')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='justification',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_justifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='module',
            name='department',
            field=models.CharField(default='Génie Informatique', max_length=100),
        ),
    ]
