# Generated by Django 4.2.7 on 2026-05-14 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('attendance', '0002_department_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='emploi_du_temps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_attendance', to='academic.emploidutemps'),
        ),
        migrations.AddField(
            model_name='module',
            name='groupes',
            field=models.ManyToManyField(blank=True, related_name='modules', to='academic.groupe'),
        ),
        migrations.AddField(
            model_name='session',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='academic.salle'),
        ),
    ]
